"""
Backend tests for iteration_19:
  - Cápsulas del Tiempo (GET / POST / visto / DELETE)
  - Auto-generación efeméride + cita del día (idempotente)
  - TTL expira_en válido y futuro
  - Marcadores [efemeride-YYYY-MM-DD] limpiados antes de devolver
  - POST/GET /api/relatos con campos historia_anio + historia_lugar
"""
import os
import time
import pytest
import requests

BASE_URL = os.environ.get('REACT_APP_BACKEND_URL', 'https://historia-connect.preview.emergentagent.com').rstrip('/')
API = f"{BASE_URL}/api"

EMAIL = 'vizcarrapulidoeddy@gmail.com'
PASSWORD = 'chronos2026'


# ---------- fixtures ----------
@pytest.fixture(scope='module')
def auth_session():
    """Backend uses cookie-based auth (chronos_token httpOnly cookie)."""
    s = requests.Session()
    r = s.post(f"{API}/auth/login", json={'correo': EMAIL, 'password': PASSWORD}, timeout=15)
    assert r.status_code == 200, f"login failed: {r.status_code} {r.text}"
    assert 'chronos_token' in s.cookies, f"no chronos_token cookie set. cookies={s.cookies.get_dict()}"
    return s


@pytest.fixture
def auth_headers(auth_session):
    # Helper to allow legacy header-based callers; we actually use the session.
    return {}


# ---------- GET /api/capsulas ----------
class TestCapsulasList:
    def test_list_anonymous_ok_and_autogenerated(self):
        r = requests.get(f"{API}/capsulas", timeout=15)
        assert r.status_code == 200, r.text
        arr = r.json()
        assert isinstance(arr, list)
        tipos = {c.get('tipo') for c in arr}
        # Must contain efemeride and cita autogenerated for the day
        assert 'efemeride' in tipos, f"missing efemeride autogenerated. tipos={tipos}"
        assert 'cita' in tipos, f"missing cita autogenerated. tipos={tipos}"

    def test_marker_is_stripped_from_text(self):
        r = requests.get(f"{API}/capsulas", timeout=15)
        assert r.status_code == 200
        for c in r.json():
            t = c.get('texto', '')
            # Should NOT include [efemeride-YYYY-MM-DD] or [cita-YYYY-MM-DD]
            assert not t.startswith('[efemeride-'), f"marker leaked in texto: {t!r}"
            assert not t.startswith('[cita-'), f"marker leaked in texto: {t!r}"

    def test_ttl_expira_en_future(self):
        r = requests.get(f"{API}/capsulas", timeout=15)
        arr = r.json()
        import datetime as dt
        now = dt.datetime.utcnow()
        for c in arr:
            ex = c.get('expira_en')
            assert ex, f"capsula sin expira_en: {c.get('_id')}"
            # ISO parse
            ex_dt = dt.datetime.fromisoformat(ex.replace('Z', '+00:00')).replace(tzinfo=None)
            assert ex_dt > now, f"expira_en no futuro: {ex} (capsula {c.get('_id')})"

    def test_idempotent_no_duplicates(self):
        """Two consecutive GETs should NOT create extra efemeride/cita for the day."""
        r1 = requests.get(f"{API}/capsulas", timeout=15).json()
        r2 = requests.get(f"{API}/capsulas", timeout=15).json()
        n_efem_1 = sum(1 for c in r1 if c.get('tipo') == 'efemeride')
        n_efem_2 = sum(1 for c in r2 if c.get('tipo') == 'efemeride')
        n_cita_1 = sum(1 for c in r1 if c.get('tipo') == 'cita')
        n_cita_2 = sum(1 for c in r2 if c.get('tipo') == 'cita')
        assert n_efem_1 == n_efem_2, f"efemerides duplicated: {n_efem_1} -> {n_efem_2}"
        assert n_cita_1 == n_cita_2, f"citas duplicated: {n_cita_1} -> {n_cita_2}"


# ---------- POST /api/capsulas + DELETE + visto ----------
class TestCapsulasCrud:
    def test_create_cronista_capsula_and_get_back(self, auth_session):
        payload = {
            'texto': 'TEST_capsula cronista iter19',
            'epoca': 'Edad Moderna',
            'anio': '1492',
            'lugar': 'Granada',
        }
        r = auth_session.post(f"{API}/capsulas", data=payload, timeout=15)
        assert r.status_code == 201, f"create failed: {r.status_code} {r.text}"
        cap = r.json()
        assert cap.get('tipo') == 'cronista'
        assert cap.get('texto') == 'TEST_capsula cronista iter19'
        assert cap.get('epoca') == 'Edad Moderna'
        assert cap.get('lugar') == 'Granada'
        assert cap.get('anio') == 1492
        assert cap.get('expira_en')
        cid = cap['_id']

        # Verify in list
        time.sleep(0.5)
        lst = requests.get(f"{API}/capsulas", timeout=15).json()
        ids = [c['_id'] for c in lst]
        assert cid in ids, f"created capsula {cid} not present in GET /capsulas"

        # Mark visto
        rv = auth_session.post(f"{API}/capsulas/{cid}/visto", timeout=15)
        assert rv.status_code == 200, rv.text
        assert rv.json().get('ok') is True

        # Cleanup: delete
        rd = auth_session.delete(f"{API}/capsulas/{cid}", timeout=15)
        assert rd.status_code == 200, rd.text
        # Verify gone
        lst2 = requests.get(f"{API}/capsulas", timeout=15).json()
        assert cid not in [c['_id'] for c in lst2]

    def test_create_validates_texto_required(self, auth_session):
        r = auth_session.post(f"{API}/capsulas", data={'texto': ''}, timeout=15)
        assert r.status_code == 400, r.text

    def test_create_validates_texto_max_320(self, auth_session):
        r = auth_session.post(f"{API}/capsulas", data={'texto': 'x' * 321}, timeout=15)
        assert r.status_code == 400, r.text

    def test_delete_requires_auth(self):
        r = requests.delete(f"{API}/capsulas/000000000000000000000000", timeout=15)
        assert r.status_code in (401, 403), r.text

    def test_cannot_delete_system_capsule(self, auth_session):
        lst = requests.get(f"{API}/capsulas", timeout=15).json()
        sys_caps = [c for c in lst if c['tipo'] in ('efemeride', 'cita')]
        assert sys_caps, "no system capsules to test against"
        rid = sys_caps[0]['_id']
        r = auth_session.delete(f"{API}/capsulas/{rid}", timeout=15)
        # Should be 403 (not owner / not cronista) or 404
        assert r.status_code in (403, 404), f"deleted a system capsule! {r.status_code} {r.text}"


# ---------- POST/GET /api/relatos with historia_anio + historia_lugar ----------
class TestRelatosHistoria:
    created_id = None

    def test_create_relato_with_historia_fields(self, auth_session):
        payload = {
            'titulo': 'TEST_iter19 historia tags',
            'contenido': 'Crónica de prueba para verificar historia_anio y historia_lugar.',
            'epoca': 'Edad Media',
            'categoria': 'Edad Media',
            'historia_anio': '1453',
            'historia_lugar': 'Constantinopla',
        }
        r = auth_session.post(f"{API}/relatos", data=payload, timeout=20)
        assert r.status_code in (200, 201), f"create relato failed: {r.status_code} {r.text}"
        body = r.json()
        # Backend wraps as { mensaje, relato }
        rel = body.get('relato', body)
        assert rel.get('historia_anio') == 1453, f"historia_anio missing/wrong in POST response: {rel.get('historia_anio')}. Full keys: {list(rel.keys())}"
        assert rel.get('historia_lugar') == 'Constantinopla', f"historia_lugar missing/wrong in POST response: {rel.get('historia_lugar')}"
        TestRelatosHistoria.created_id = rel.get('_id') or rel.get('id')
        assert TestRelatosHistoria.created_id

    def test_get_relato_by_id_includes_historia(self, auth_session):
        rid = TestRelatosHistoria.created_id
        assert rid, "depends on previous test"
        r = auth_session.get(f"{API}/relatos/{rid}", timeout=15)
        assert r.status_code == 200, r.text
        body = r.json()
        rel = body.get('relato', body)
        assert rel.get('historia_anio') == 1453, f"got {rel.get('historia_anio')}"
        assert rel.get('historia_lugar') == 'Constantinopla'

    def test_get_relatos_list_includes_historia(self, auth_session):
        r = auth_session.get(f"{API}/relatos", timeout=15)
        assert r.status_code == 200
        payload = r.json()
        arr = payload if isinstance(payload, list) else (payload.get('relatos') or payload.get('publicaciones') or [])
        target = next((x for x in arr if (x.get('_id') == TestRelatosHistoria.created_id)), None)
        assert target, f"created relato not in list (n={len(arr)})"
        assert target.get('historia_anio') == 1453
        assert target.get('historia_lugar') == 'Constantinopla'

    def test_cleanup_delete_relato(self, auth_session):
        rid = TestRelatosHistoria.created_id
        if not rid:
            pytest.skip("nothing to clean")
        auth_session.delete(f"{API}/relatos/{rid}", timeout=15)
